namespace LunaApp.Services.Reports.Html;

/// <summary>Small shared fragments used by both single-reel and project report builders.</summary>
internal static class HtmlDocumentParts
{
    public static string Footer() =>
        $"""
            <footer class="footer">
                <p>Generated by Luna · {DateTime.Now:yyyy-MM-dd HH:mm}</p>
            </footer>
        """;
}
